In [ ]:
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np


def load_train(path):
    features_train = np.load(path + 'train_features.npy')
    target_train = np.load(path + 'train_target.npy')
    features_train = features_train.reshape(features_train.shape[0], 28 * 28) / 255.
    return features_train, target_train


def create_model(input_shape):
    model = Sequential()
    model.add(Dense(10, input_shape=input_shape, activation='softmax'))
    model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy',
                  metrics=['acc'])

    return model


def train_model(model, train_data, test_data, batch_size=32, epochs=5,
               steps_per_epoch=None, validation_steps=None):

    features_train, target_train = train_data
    features_test, target_test = test_data
    model.fit(features_train, target_train, 
              validation_data=(features_test, target_test),
              batch_size=batch_size, epochs=epochs,
              steps_per_epoch=steps_per_epoch,
              validation_steps=validation_steps,
              verbose=2, shuffle=True)

    return model 

In [6]:
import numpy as np 

In [14]:
def convolve(sequence, weights):
    convolution = np.zeros(len(sequence) - len(weights) + 1)
    print(convolution)
    for i in range(convolution.shape[0]):
        print(convolution.shapepe[0])
        convolution[i] = np.sum(weights * sequence[i:i + len(weights)])
    return convolution 

In [15]:
s = [2, 3, 5, 7, 11]
w = [-1, 1] 

In [37]:
convolution = np.zeros(len(s) - len(w) + 1)
print(convolution)
for i in range(convolution.shape[0]):
    print(convolution.shape[0])
    convolution[i] = np.sum(np.array(w) * np.array(s[i:i + len(w)]))
print(convolution)

[0. 0. 0. 0.]
4
4
4
4
[1. 2. 2. 4.]


In [89]:
s = np.array([[2, 1, 3], 
     [4, 0, 2], 
     [1, 5, 6]])
w = np.array([[-1, -2], 
     [1,   2]])

In [95]:
convolution = [np.zeros(len(s) - len(w) + 1) for i in range(len(w))]
for i in range(len(w[0])):
    for j in range(len(w)):
        convolution[i][j] = sum(sum(np.array(s[i:i+len(w), j:j+len(w)] * w)))
        print(convolution[i][j])

0.0
-3.0
7.0
13.0


In [86]:
for i in range(len(w[0])):
    for j in range(len(w)):
        print(np.array(s[i:i+len(w), j:j+len(w)]))

[[2 1]
 [4 0]]
[[1 3]
 [0 2]]
[[4 0]
 [1 5]]
[[0 2]
 [5 6]]


In [96]:
convolution

[array([ 0., -3.]), array([ 7., 13.])]